FROM golang:1.24-alpine

RUN apk add build-base

WORKDIR /app

COPY . .

EXPOSE 80
EXPOSE 2345

RUN apk add --no-cache curl tzdata

RUN go install github.com/cosmtrek/air@v1.50.0
RUN go install github.com/go-delve/delve/cmd/dlv@latest